### ISSUE TITLE
Ansible cannot detect dockpulp module

### ISSUE THREAD

**Issue by rhjostone** [release-engineering/dockpulp-ansible#3]
Installing dockpulp-ansible from github works as expected:

```bash
$ ansible-galaxy collection install git+https://github.com/release-engineering/dockpulp-ansible
```

```bash
$ ansible-galaxy collection list | grep dockpulp_ansible
release_engineering.dockpulp_ansible 0.1.0  
```

However, Ansible doesn't seem to be able to detect the dockpulp_repo module.

```bash
$ cat dockpulp.yml 
- name: create dockpulp repositories on rhel9
  hosts: localhost
  collections:
    - release_engineering.dockpulp_ansible
  tasks:
  - name: Add rhceph-4-tools-for-rhel-9-x86_64-rpms cdn repo
    dockpulp_repo:
      env: stage
      dockpulp_user: fakeuser
      dockpulp_password: fakeuserPassw0rd
      repo_name: rhceph-4-rhel9
      namespace: rhceph
      content_url: /content/dist/containers/rhel9/multiarch/containers/redhat-rhceph-rhceph-4-rhel9
      description: This is a test repo for create dockpulp repo
      distribution: ga

$ ansible-playbook --check dockpulp.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'
ERROR! couldn't resolve module/action 'dockpulp_repo'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/jostone/Projects/gerrit/rcm-ansible/dockpulp.yml': line 6, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
  - name: Add rhceph-4-tools-for-rhel-9-x86_64-rpms cdn repo
    ^ here
```

Is there supposed to be a different way of invoking it?

**Comment by hongweiliu17** [comment]
@rhjostone This repo has not been published as a collection. I have a jira [CWFCONF-1417](https://issues.redhat.com/browse/CWFCONF-1417) tracking it. You may git clone the repo in your ansible script before calling `dockpulp_repo` now

**Comment by rhjostone** [comment]
@hongweiliu17 So instead of:

```bash
$ ansible-galaxy collection install git+https://github.com/release-engineering/dockpulp-ansible
```

Do this instead to run it in my local directory:

```bash
$ git clone https://github.com/release-engineering/dockpulp-ansible collections/ansible_collections/release_engineering/dockpulp_ansible
```

I tried doing the above earlier, but I get the same error unless I moved files into a plugins folder:

```bash
$ tree collections/ansible_collections/release_engineering/dockpulp_ansible
collections/ansible_collections/release_engineering/dockpulp_ansible
├── COPYING
├── galaxy.yml
├── plugins
│   ├── modules
│   │   └── dockpulp_repo.py
│   └── module_utils
│       └── dockpulp_common.py
├── README.rst
├── requirements.txt
├── tests
│   ├── conftest.py
│   ├── requirements.txt
│   ├── test_dockpulp_common.py
│   ├── test_dockpulp.py
│   └── utils.py
└── tox.ini
```

I get a different error though when trying to include this in a simple role:

```
fatal: [localhost]: FAILED! => 
  msg: Could not find imported module support code for ansible_collections.release_engineering.dockpulp_ansible.plugins.modules.dockpulp_repo.  Looked for (['ansible.module_utils.dockpulp_common.describe_changes', 'ansible.module_utils.dockpulp_common'])
```

**Comment by hongweiliu17** [comment]
I think you may use the module in your playbook like below, without `ansible-galaxy`:
```
- name: create dockpulp repositories on rhel9
  hosts: localhost
  tasks:
  - name: Clone dockpulp-ansible git repository
        git:
        ...
  - name: Move collection module_utils to module_utils dir
        copy:
          src: ../dockpulp-ansible/module_utils/
          dest: ../module_utils/
          mode: 0644
          ...
  - name: Move collection modules to library dir
          src: ../dockpulp-ansible/library/
          dest: ../library/
          mode: 0644
          ….
    - name: Add rhceph-4-tools-for-rhel-9-x86_64-rpms cdn repo
      dockpulp_repo:
        env: stage
        dockpulp_user: fakeuser
        dockpulp_password: fakeuserPassw0rd
        repo_name: rhceph-4-rhel9
        namespace: rhceph
        content_url: /content/dist/containers/rhel9/multiarch/containers/redhat-rhceph-rhceph-4-rhel9
        description: This is a test repo for create dockpulp repo
        distribution: ga
```
